version: "3.9"

services:
  it_has_alternatives:
    network_mode: "host"        
    build: 
      context: ./
      dockerfile: ./Dockerfile
    image: yingshaoxo/it_has_alternatives
    # expose:
    #   - "5550"
    #   - "5551"
    #   - "5552"
    #   - "5553"
    # ports:
    #   - "5550:5550"
    #   - "5551:5551"
    #   - "5552:5552"
    #   - "5553:5553"
    environment:
      - ADMIN_EMAIL=yingshaoxo@gmail.com
      - MONGO_DB_URL=mongodb://yingshaoxo:yingshaoxo@127.0.0.1:27017/?authMechanism=PLAIN
    restart: unless-stopped
