## in /etc/hosts
# 127.0.0.1 alternatives.domain.local user_alternatives.domain.local admin_alternatives.domain.local

# tcp:
#   routers:
#     next_traefik_router:
#       entryPoints:
#         - web
#       # rule: "HostSNI(`*`)"
#       # rule: "!HostSNI(`alternatives.ai-tools-online.xyz`)"
#       rule: "HostSNI(`auth.weloveparty.ai-tools-online.xyz`)"
#       service: next_traefik_service
#       tls:
#          passthrough: true
#   services:
#     next_traefik_service:
#       loadBalancer:
#         servers:
#           - address: 144.202.109.163:810
#           # - address: 127.0.0.1:810

http:
  routers:
    # next_traefik_router:
    #   entryPoints:
    #     - web
    #     - websecure
    #   # rule: "!Host(`alternatives.ai-tools-online.xyz`)"
    #   rule: "HostRegexp(`(.*)weloveparty(.*)`)"
    #   service: next_traefik_service
    next_traefik_router_for_style_shop:
      entryPoints:
        - web
        - websecure
      rule: "HostRegexp(`(.*)style_shop(.*)`)"
      service: next_traefik_service_for_style_shop
    its_alternative_router_for_visitor_operations:
      entryPoints:
        - web
        - websecure
      # rule: "(Host(`alternatives.ai-tools-online.xyz`) || Host(`alternatives.domain.local`)) && PathPrefix(`/it_has_alternatives/`)"
      rule: "Host(`alternatives.ai-tools-online.xyz`) || Host(`alternatives.domain.local`)"
      middlewares:
        - cros_allow_all
      service: backend_service_for_visitor
    its_alternative_router_for_users_operations:
      entryPoints:
        - web
        - websecure
      rule: "Host(`user_alternatives.ai-tools-online.xyz`) || Host(`user_alternatives.domain.local`)"
      middlewares:
        - cros_allow_all
        - my_jwt_auth
      service: backend_service_for_user
    its_alternative_router_for_admin_operations:
      entryPoints:
        - web
        - websecure
      rule: "Host(`admin_alternatives.ai-tools-online.xyz`) || Host(`admin_alternatives.domain.local`)"
      middlewares:
        - cros_allow_all
        - my_admin_jwt_auth
      service: backend_service_for_admin

  middlewares:
    cros_allow_all:
      headers:
        accessControlAllowMethods: "*"
        accessControlAllowHeaders: "*"
        accessControlAllowOriginList: "*"
        accessControlMaxAge: 100
        addVaryHeader: true
    my_grpcweb:
      grpcWeb:
        allowOrigins:
          - "*"
    my_jwt_auth:
        forwardAuth:
          # address: "http://it_has_alternatives:5550/v1/jwt_auth_gateway/"
          # address: http://host.docker.internal:5550/v1/jwt_auth_gateway/
          address: "http://127.0.0.1:5550/v1/jwt_auth_gateway/"
          authResponseHeaders:
              - "email" # jwt_auth_gateway will put this header to the original request
    my_admin_jwt_auth:
        forwardAuth:
          address: "http://127.0.0.1:5550/v1/admin_jwt_auth_gateway/"
          authResponseHeaders:
              - "email" # jwt_auth_gateway will put this header to the original request

  services:
    # next_traefik_service:
    #   loadBalancer:
    #     servers:
    #       - url: http://127.0.0.1:810
    next_traefik_service_for_style_shop:
        servers:
          - url: http://127.0.0.1:811
    backend_service_for_visitor:
      loadBalancer:
        servers:
          # - url: http://it_has_alternatives:5551
          # - url: http://host.docker.internal:5551
          - url: http://127.0.0.1:5551
        passHostHeader: true
    backend_service_for_user:
      loadBalancer:
        servers:
          - url: http://127.0.0.1:5552
        passHostHeader: true
    backend_service_for_admin:
      loadBalancer:
        servers:
          - url: http://127.0.0.1:5553
        passHostHeader: true
