## in /etc/hosts
# 127.0.0.1 alternatives.domain.local admin_alternatives.domain.local

http:
  routers:
    its_alternative_router_for_visitor_operations:
      entryPoints:
        - web
        - websecure
      # rule: "(Host(`alternatives.ai-tools-online.xyz`) || Host(`alternatives.domain.local`)) && (PathPrefix(`/it_has_alternatives/get_special_jwt/`) || PathPrefix(`/it_has_alternatives/search_alternatives/`) || PathPrefix(`/it_has_alternatives/get_an_object/`) || PathPrefix(`/it_has_alternatives/is_jwt_ok/`))"
      rule: "Host(`alternatives.ai-tools-online.xyz`) || Host(`alternatives.domain.local`)"
      middlewares:
        - cros_allow_all
      service: backend_service_for_visitor
    its_alternative_router_for_admin_operations:
      entryPoints:
        - web
        - websecure
      # rule: "(Host(`admin_alternatives.ai-tools-online.xyz`) || Host(`admin_alternatives.domain.local`)) || (PathPrefix(`/it_has_alternatives/`))"
      rule: "Host(`admin_alternatives.ai-tools-online.xyz`) || Host(`admin_alternatives.domain.local`)"
      middlewares:
        - cros_allow_all
        - my_admin_jwt_auth
      service: backend_service_for_admin
    for_other_requests_router:
      entryPoints:
        - web
        - websecure
      rule: "Host(`*`)"
      service: next_traefik_service

  middlewares:
    cros_allow_all:
      headers:
        accessControlAllowMethods: "*"
        accessControlAllowHeaders: "*"
        accessControlAllowOriginList: "*"
        accessControlMaxAge: 100
        addVaryHeader: true
    my_grpcweb:
      grpcWeb:
        allowOrigins:
          - "*"
    my_jwt_auth:
        forwardAuth:
          address: "http://it_has_alternatives:5550/v1/jwt_auth_gateway/"
          authResponseHeaders:
              - "email" # jwt_auth_gateway will put this header to the original request
    my_admin_jwt_auth:
        forwardAuth:
          address: "http://it_has_alternatives:5550/v1/admin_jwt_auth_gateway/"
          authResponseHeaders:
              - "email" # jwt_auth_gateway will put this header to the original request

  services:
    backend_service_for_visitor:
      loadBalancer:
        servers:
          - url: http://it_has_alternatives:5551
        passHostHeader: true
    backend_service_for_admin:
      loadBalancer:
        servers:
          - url: http://it_has_alternatives:5552
        passHostHeader: true
    next_traefik_service:
      loadBalancer:
        servers:
          - url: h2c://127.0.0.1:808
        passHostHeader: true
